service: GarageDoor # NOTE: update this with your service name

custom:
  user: ${ssm:myqUser~true}
  pass: ${ssm:myqPassword~true}
  apiKey: ${ssm:apiSecretKey~true}

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  deploymentBucket:
    name: com.serverless.${self:provider.region}.8675309

functions:
  status:
    handler: handler.status
    environment:
      USER: ${self:custom.user}
      PASS: ${self:custom.pass}
      KEY: ${self:custom.apiKey}
    memorySize: 256
    timeout: 60
    events:
      - http:
          path: door/status
          method: get

plugins:
  - serverless-plugin-create-deployment-bucket