service: GarageDoor # NOTE: update this with your service name

custom:
  user: ${ssm:myqUser~true}
  pass: ${ssm:myqPassword~true}
  apiKey: ${ssm:apiSecretKey~true}

provider:
  name: aws
  runtime: nodejs8.10

functions:
  status:
    handler: handler.status
    environment:
      USER: ${self:custom.user}
      PASS: ${self:custom.pass}
      KEY: ${self:custom.apiKey}
    memorySize: 256
    timeout: 30