service: GarageDoor # NOTE: update this with your service name

custom:
  user: ${ssm:myqUser~true}
  pass: ${ssm:myqPassword~true}
  apiKey: ${ssm:apiSecretKey~true}

provider:
  name: aws
  runtime: nodejs8.10
  region: us-east-1
  deploymentBucket:
    name: com.serverless.${self:provider.region}.8675309

functions:
  status:
    handler: door.status
    environment:
      USER: ${self:custom.user}
      PASS: ${self:custom.pass}
    memorySize: 256
    timeout: 60
    events:
      - http:
          path: door/status
          method: get
          authorizer: authorizeUser
  open:
    handler: door.open
    environment:
      USER: ${self:custom.user}
      PASS: ${self:custom.pass}
    memorySize: 256
    timeout: 60
    events:
      - http:
          path: door/open
          method: get
          authorizer: authorizeUser

  authorizeUser:
    handler: authorizer.user
    environment:
      KEY: ${self:custom.apiKey}

plugins:
  - serverless-plugin-create-deployment-bucket